name: ledgerone
description: "Tracks all assets you own, Knows Where the live, Lets you manually log what happens and can optionally compute a usd portfollo"

publish_to: "none"

version: 0.9.3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  http: ^1.6.0

  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^4.2.0
  sqlite3_flutter_libs: ^0.5.41
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
